### ISSUE TITLE
Formatting issue when using economy plugins that edit text color and formatting.

### ISSUE THREAD

**Issue by addidotlol** [WiIIiam278/HuskTowns#127]
Hey! I noticed that when using UltraEconomy (https://www.spigotmc.org/resources/ultra-economy.83374/) the text when depositing into town coffers changes with what the economy plugin name is set to. It should probably be reset after showing the currency. 

I've only seen this issue with HuskTowns so I've decided against reporting this to UltraEconomy but if you'd like I can report it there too.

![image](https://user-images.githubusercontent.com/54275575/179809734-1b2bb8b8-08da-455c-a755-d11c0a888c8c.png)
![image](https://user-images.githubusercontent.com/54275575/179809787-40d8b358-efaf-428b-acd7-837ce1a04299.png)
![image](https://user-images.githubusercontent.com/54275575/179809848-252f02d4-1613-4742-a6b1-ad9ce4ec2637.png)

**Comment by WiIIiam278** [comment]
Hi there. So, this issue is caused by two things.
- HuskTowns uses MineDown for formatting. MineDown does not support in-line
resetting, rather [bracket syntax](color)
- Vault’s API for currency formatting doesn’t intend for you to use
formatting codes within it

Remove the yellow and bold formatting from your currency codes and the
issue should go away-as it stands it’s not really a HuskTowns issue, more a
mix of questionable API usage and MineDown format incompatibility.
