### ISSUE TITLE
/t invite missing from shortcut list and /t info permission not in husktowns.command.town.* set

### ISSUE THREAD

**Issue by Skizzles** [WiIIiam278/HuskTowns#128]
/t info shows no permission even with husktowns.player, only works for those with administrator perms

/t invite shows error_invalid_subcommand and only works with /invite

Only appeared after upgrade to HuskTowns 1.8

**Comment by Skizzles** [comment]
For reference @WiIIiam278 the /t invite isnt even shown in /t help like its not registering properly.

**Comment by WiIIiam278** [comment]
/t invite should be a shortcut command -- and it looks like I just forgot to add it.
https://github.com/WiIIiam278/HuskTowns/blob/75068f986ca9a7cc89e51bc8d469a3da0ac9c9f1/bukkit/src/main/java/net/william278/husktowns/command/TownCommand.java#L67-L78
Should be an easy fix.

As for the permission issue with /t info, that's caused by the `husktowns.player` node, which ultimately references `husktowns.commands.town.*` not containing `husktowns.command.town.info`
https://github.com/WiIIiam278/HuskTowns/blob/75068f986ca9a7cc89e51bc8d469a3da0ac9c9f1/bukkit/src/main/resources/plugin.yml#L184-L201
Also should be an easy fix when I have a sec, or feel free to PR.
